//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MvcApplicationDBModel", "pk_keyfile", "tbl_Products", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PacketIntranet.Models.tbl_Products), "tbl_files", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PacketIntranet.Models.tbl_files), true)]
[assembly: EdmRelationshipAttribute("MvcApplicationDBModel", "pk_key2", "tbl_Origins", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PacketIntranet.Models.tbl_Origins), "tbl_Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PacketIntranet.Models.tbl_Products), true)]
[assembly: EdmRelationshipAttribute("MvcApplicationDBModel", "pk_key1", "tbl_ProductTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PacketIntranet.Models.tbl_ProductTypes), "tbl_Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PacketIntranet.Models.tbl_Products), true)]
[assembly: EdmRelationshipAttribute("MvcApplicationDBModel", "pk_keyUnit", "tbl_Units", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PacketIntranet.Models.tbl_Units), "tbl_Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PacketIntranet.Models.tbl_Products), true)]

#endregion

namespace PacketIntranet.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MvcApplicationDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MvcApplicationDBEntities object using the connection string found in the 'MvcApplicationDBEntities' section of the application configuration file.
        /// </summary>
        public MvcApplicationDBEntities() : base("name=MvcApplicationDBEntities", "MvcApplicationDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MvcApplicationDBEntities object.
        /// </summary>
        public MvcApplicationDBEntities(string connectionString) : base(connectionString, "MvcApplicationDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MvcApplicationDBEntities object.
        /// </summary>
        public MvcApplicationDBEntities(EntityConnection connection) : base(connection, "MvcApplicationDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Articles> tbl_Articles
        {
            get
            {
                if ((_tbl_Articles == null))
                {
                    _tbl_Articles = base.CreateObjectSet<tbl_Articles>("tbl_Articles");
                }
                return _tbl_Articles;
            }
        }
        private ObjectSet<tbl_Articles> _tbl_Articles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_files> tbl_files
        {
            get
            {
                if ((_tbl_files == null))
                {
                    _tbl_files = base.CreateObjectSet<tbl_files>("tbl_files");
                }
                return _tbl_files;
            }
        }
        private ObjectSet<tbl_files> _tbl_files;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Origins> tbl_Origins
        {
            get
            {
                if ((_tbl_Origins == null))
                {
                    _tbl_Origins = base.CreateObjectSet<tbl_Origins>("tbl_Origins");
                }
                return _tbl_Origins;
            }
        }
        private ObjectSet<tbl_Origins> _tbl_Origins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Products> tbl_Products
        {
            get
            {
                if ((_tbl_Products == null))
                {
                    _tbl_Products = base.CreateObjectSet<tbl_Products>("tbl_Products");
                }
                return _tbl_Products;
            }
        }
        private ObjectSet<tbl_Products> _tbl_Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_ProductTypes> tbl_ProductTypes
        {
            get
            {
                if ((_tbl_ProductTypes == null))
                {
                    _tbl_ProductTypes = base.CreateObjectSet<tbl_ProductTypes>("tbl_ProductTypes");
                }
                return _tbl_ProductTypes;
            }
        }
        private ObjectSet<tbl_ProductTypes> _tbl_ProductTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Relationship> tbl_Relationship
        {
            get
            {
                if ((_tbl_Relationship == null))
                {
                    _tbl_Relationship = base.CreateObjectSet<tbl_Relationship>("tbl_Relationship");
                }
                return _tbl_Relationship;
            }
        }
        private ObjectSet<tbl_Relationship> _tbl_Relationship;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Units> tbl_Units
        {
            get
            {
                if ((_tbl_Units == null))
                {
                    _tbl_Units = base.CreateObjectSet<tbl_Units>("tbl_Units");
                }
                return _tbl_Units;
            }
        }
        private ObjectSet<tbl_Units> _tbl_Units;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Articles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Articles(tbl_Articles tbl_Articles)
        {
            base.AddObject("tbl_Articles", tbl_Articles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_files EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_files(tbl_files tbl_files)
        {
            base.AddObject("tbl_files", tbl_files);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Origins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Origins(tbl_Origins tbl_Origins)
        {
            base.AddObject("tbl_Origins", tbl_Origins);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Products(tbl_Products tbl_Products)
        {
            base.AddObject("tbl_Products", tbl_Products);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_ProductTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_ProductTypes(tbl_ProductTypes tbl_ProductTypes)
        {
            base.AddObject("tbl_ProductTypes", tbl_ProductTypes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Relationship EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Relationship(tbl_Relationship tbl_Relationship)
        {
            base.AddObject("tbl_Relationship", tbl_Relationship);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Units EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Units(tbl_Units tbl_Units)
        {
            base.AddObject("tbl_Units", tbl_Units);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplicationDBModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplicationDBModel", Name="tbl_Articles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Articles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Articles object.
        /// </summary>
        /// <param name="articleId">Initial value of the ArticleId property.</param>
        public static tbl_Articles Createtbl_Articles(global::System.Int32 articleId)
        {
            tbl_Articles tbl_Articles = new tbl_Articles();
            tbl_Articles.ArticleId = articleId;
            return tbl_Articles;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ArticleId
        {
            get
            {
                return _ArticleId;
            }
            set
            {
                if (_ArticleId != value)
                {
                    OnArticleIdChanging(value);
                    ReportPropertyChanging("ArticleId");
                    _ArticleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ArticleId");
                    OnArticleIdChanged();
                }
            }
        }
        private global::System.Int32 _ArticleId;
        partial void OnArticleIdChanging(global::System.Int32 value);
        partial void OnArticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FeatureImage
        {
            get
            {
                return _FeatureImage;
            }
            set
            {
                OnFeatureImageChanging(value);
                ReportPropertyChanging("FeatureImage");
                _FeatureImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FeatureImage");
                OnFeatureImageChanged();
            }
        }
        private global::System.String _FeatureImage;
        partial void OnFeatureImageChanging(global::System.String value);
        partial void OnFeatureImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReadMore
        {
            get
            {
                return _ReadMore;
            }
            set
            {
                OnReadMoreChanging(value);
                ReportPropertyChanging("ReadMore");
                _ReadMore = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReadMore");
                OnReadMoreChanged();
            }
        }
        private global::System.String _ReadMore;
        partial void OnReadMoreChanging(global::System.String value);
        partial void OnReadMoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Meta
        {
            get
            {
                return _Meta;
            }
            set
            {
                OnMetaChanging(value);
                ReportPropertyChanging("Meta");
                _Meta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Meta");
                OnMetaChanged();
            }
        }
        private global::System.String _Meta;
        partial void OnMetaChanging(global::System.String value);
        partial void OnMetaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PostDate
        {
            get
            {
                return _PostDate;
            }
            set
            {
                OnPostDateChanging(value);
                ReportPropertyChanging("PostDate");
                _PostDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostDate");
                OnPostDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PostDate;
        partial void OnPostDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPostDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplicationDBModel", Name="tbl_files")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_files : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_files object.
        /// </summary>
        /// <param name="fil_Id">Initial value of the Fil_Id property.</param>
        public static tbl_files Createtbl_files(global::System.Int32 fil_Id)
        {
            tbl_files tbl_files = new tbl_files();
            tbl_files.Fil_Id = fil_Id;
            return tbl_files;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Fil_Id
        {
            get
            {
                return _Fil_Id;
            }
            set
            {
                if (_Fil_Id != value)
                {
                    OnFil_IdChanging(value);
                    ReportPropertyChanging("Fil_Id");
                    _Fil_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Fil_Id");
                    OnFil_IdChanged();
                }
            }
        }
        private global::System.Int32 _Fil_Id;
        partial void OnFil_IdChanging(global::System.Int32 value);
        partial void OnFil_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pro_Id
        {
            get
            {
                return _Pro_Id;
            }
            set
            {
                OnPro_IdChanging(value);
                ReportPropertyChanging("Pro_Id");
                _Pro_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pro_Id");
                OnPro_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Pro_Id;
        partial void OnPro_IdChanging(Nullable<global::System.Int32> value);
        partial void OnPro_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fil_Name
        {
            get
            {
                return _Fil_Name;
            }
            set
            {
                OnFil_NameChanging(value);
                ReportPropertyChanging("Fil_Name");
                _Fil_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fil_Name");
                OnFil_NameChanged();
            }
        }
        private global::System.String _Fil_Name;
        partial void OnFil_NameChanging(global::System.String value);
        partial void OnFil_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplicationDBModel", "pk_keyfile", "tbl_Products")]
        public tbl_Products tbl_Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Products>("MvcApplicationDBModel.pk_keyfile", "tbl_Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Products>("MvcApplicationDBModel.pk_keyfile", "tbl_Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Products> tbl_ProductsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Products>("MvcApplicationDBModel.pk_keyfile", "tbl_Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Products>("MvcApplicationDBModel.pk_keyfile", "tbl_Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplicationDBModel", Name="tbl_Origins")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Origins : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Origins object.
        /// </summary>
        /// <param name="ori_Id">Initial value of the Ori_Id property.</param>
        public static tbl_Origins Createtbl_Origins(global::System.Int32 ori_Id)
        {
            tbl_Origins tbl_Origins = new tbl_Origins();
            tbl_Origins.Ori_Id = ori_Id;
            return tbl_Origins;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ori_Id
        {
            get
            {
                return _Ori_Id;
            }
            set
            {
                if (_Ori_Id != value)
                {
                    OnOri_IdChanging(value);
                    ReportPropertyChanging("Ori_Id");
                    _Ori_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Ori_Id");
                    OnOri_IdChanged();
                }
            }
        }
        private global::System.Int32 _Ori_Id;
        partial void OnOri_IdChanging(global::System.Int32 value);
        partial void OnOri_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ori_Conutry
        {
            get
            {
                return _Ori_Conutry;
            }
            set
            {
                OnOri_ConutryChanging(value);
                ReportPropertyChanging("Ori_Conutry");
                _Ori_Conutry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ori_Conutry");
                OnOri_ConutryChanged();
            }
        }
        private global::System.String _Ori_Conutry;
        partial void OnOri_ConutryChanging(global::System.String value);
        partial void OnOri_ConutryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descriptions
        {
            get
            {
                return _Descriptions;
            }
            set
            {
                OnDescriptionsChanging(value);
                ReportPropertyChanging("Descriptions");
                _Descriptions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descriptions");
                OnDescriptionsChanged();
            }
        }
        private global::System.String _Descriptions;
        partial void OnDescriptionsChanging(global::System.String value);
        partial void OnDescriptionsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplicationDBModel", "pk_key2", "tbl_Products")]
        public EntityCollection<tbl_Products> tbl_Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Products>("MvcApplicationDBModel.pk_key2", "tbl_Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Products>("MvcApplicationDBModel.pk_key2", "tbl_Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplicationDBModel", Name="tbl_Products")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Products : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Products object.
        /// </summary>
        /// <param name="pro_Id">Initial value of the Pro_Id property.</param>
        public static tbl_Products Createtbl_Products(global::System.Int32 pro_Id)
        {
            tbl_Products tbl_Products = new tbl_Products();
            tbl_Products.Pro_Id = pro_Id;
            return tbl_Products;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Pro_Id
        {
            get
            {
                return _Pro_Id;
            }
            set
            {
                if (_Pro_Id != value)
                {
                    OnPro_IdChanging(value);
                    ReportPropertyChanging("Pro_Id");
                    _Pro_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Pro_Id");
                    OnPro_IdChanged();
                }
            }
        }
        private global::System.Int32 _Pro_Id;
        partial void OnPro_IdChanging(global::System.Int32 value);
        partial void OnPro_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProType_Id
        {
            get
            {
                return _ProType_Id;
            }
            set
            {
                OnProType_IdChanging(value);
                ReportPropertyChanging("ProType_Id");
                _ProType_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProType_Id");
                OnProType_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProType_Id;
        partial void OnProType_IdChanging(Nullable<global::System.Int32> value);
        partial void OnProType_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ori_Id
        {
            get
            {
                return _Ori_Id;
            }
            set
            {
                OnOri_IdChanging(value);
                ReportPropertyChanging("Ori_Id");
                _Ori_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ori_Id");
                OnOri_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Ori_Id;
        partial void OnOri_IdChanging(Nullable<global::System.Int32> value);
        partial void OnOri_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pro_Name
        {
            get
            {
                return _Pro_Name;
            }
            set
            {
                OnPro_NameChanging(value);
                ReportPropertyChanging("Pro_Name");
                _Pro_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pro_Name");
                OnPro_NameChanged();
            }
        }
        private global::System.String _Pro_Name;
        partial void OnPro_NameChanging(global::System.String value);
        partial void OnPro_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pro_Images
        {
            get
            {
                return _Pro_Images;
            }
            set
            {
                OnPro_ImagesChanging(value);
                ReportPropertyChanging("Pro_Images");
                _Pro_Images = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pro_Images");
                OnPro_ImagesChanged();
            }
        }
        private global::System.String _Pro_Images;
        partial void OnPro_ImagesChanging(global::System.String value);
        partial void OnPro_ImagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pro_Price
        {
            get
            {
                return _Pro_Price;
            }
            set
            {
                OnPro_PriceChanging(value);
                ReportPropertyChanging("Pro_Price");
                _Pro_Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pro_Price");
                OnPro_PriceChanged();
            }
        }
        private Nullable<global::System.Int32> _Pro_Price;
        partial void OnPro_PriceChanging(Nullable<global::System.Int32> value);
        partial void OnPro_PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pro_Warranty
        {
            get
            {
                return _Pro_Warranty;
            }
            set
            {
                OnPro_WarrantyChanging(value);
                ReportPropertyChanging("Pro_Warranty");
                _Pro_Warranty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pro_Warranty");
                OnPro_WarrantyChanged();
            }
        }
        private global::System.String _Pro_Warranty;
        partial void OnPro_WarrantyChanging(global::System.String value);
        partial void OnPro_WarrantyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descriptions
        {
            get
            {
                return _Descriptions;
            }
            set
            {
                OnDescriptionsChanging(value);
                ReportPropertyChanging("Descriptions");
                _Descriptions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descriptions");
                OnDescriptionsChanged();
            }
        }
        private global::System.String _Descriptions;
        partial void OnDescriptionsChanging(global::System.String value);
        partial void OnDescriptionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Unit_Id
        {
            get
            {
                return _Unit_Id;
            }
            set
            {
                OnUnit_IdChanging(value);
                ReportPropertyChanging("Unit_Id");
                _Unit_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Unit_Id");
                OnUnit_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Unit_Id;
        partial void OnUnit_IdChanging(Nullable<global::System.Int32> value);
        partial void OnUnit_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplicationDBModel", "pk_keyfile", "tbl_files")]
        public EntityCollection<tbl_files> tbl_files
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_files>("MvcApplicationDBModel.pk_keyfile", "tbl_files");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_files>("MvcApplicationDBModel.pk_keyfile", "tbl_files", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplicationDBModel", "pk_key2", "tbl_Origins")]
        public tbl_Origins tbl_Origins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Origins>("MvcApplicationDBModel.pk_key2", "tbl_Origins").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Origins>("MvcApplicationDBModel.pk_key2", "tbl_Origins").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Origins> tbl_OriginsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Origins>("MvcApplicationDBModel.pk_key2", "tbl_Origins");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Origins>("MvcApplicationDBModel.pk_key2", "tbl_Origins", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplicationDBModel", "pk_key1", "tbl_ProductTypes")]
        public tbl_ProductTypes tbl_ProductTypes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_ProductTypes>("MvcApplicationDBModel.pk_key1", "tbl_ProductTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_ProductTypes>("MvcApplicationDBModel.pk_key1", "tbl_ProductTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_ProductTypes> tbl_ProductTypesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_ProductTypes>("MvcApplicationDBModel.pk_key1", "tbl_ProductTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_ProductTypes>("MvcApplicationDBModel.pk_key1", "tbl_ProductTypes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplicationDBModel", "pk_keyUnit", "tbl_Units")]
        public tbl_Units tbl_Units
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Units>("MvcApplicationDBModel.pk_keyUnit", "tbl_Units").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Units>("MvcApplicationDBModel.pk_keyUnit", "tbl_Units").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Units> tbl_UnitsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Units>("MvcApplicationDBModel.pk_keyUnit", "tbl_Units");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Units>("MvcApplicationDBModel.pk_keyUnit", "tbl_Units", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplicationDBModel", Name="tbl_ProductTypes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_ProductTypes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_ProductTypes object.
        /// </summary>
        /// <param name="proType_Id">Initial value of the ProType_Id property.</param>
        public static tbl_ProductTypes Createtbl_ProductTypes(global::System.Int32 proType_Id)
        {
            tbl_ProductTypes tbl_ProductTypes = new tbl_ProductTypes();
            tbl_ProductTypes.ProType_Id = proType_Id;
            return tbl_ProductTypes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProType_Id
        {
            get
            {
                return _ProType_Id;
            }
            set
            {
                if (_ProType_Id != value)
                {
                    OnProType_IdChanging(value);
                    ReportPropertyChanging("ProType_Id");
                    _ProType_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProType_Id");
                    OnProType_IdChanged();
                }
            }
        }
        private global::System.Int32 _ProType_Id;
        partial void OnProType_IdChanging(global::System.Int32 value);
        partial void OnProType_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProType_Name
        {
            get
            {
                return _ProType_Name;
            }
            set
            {
                OnProType_NameChanging(value);
                ReportPropertyChanging("ProType_Name");
                _ProType_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProType_Name");
                OnProType_NameChanged();
            }
        }
        private global::System.String _ProType_Name;
        partial void OnProType_NameChanging(global::System.String value);
        partial void OnProType_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descriptions
        {
            get
            {
                return _Descriptions;
            }
            set
            {
                OnDescriptionsChanging(value);
                ReportPropertyChanging("Descriptions");
                _Descriptions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descriptions");
                OnDescriptionsChanged();
            }
        }
        private global::System.String _Descriptions;
        partial void OnDescriptionsChanging(global::System.String value);
        partial void OnDescriptionsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplicationDBModel", "pk_key1", "tbl_Products")]
        public EntityCollection<tbl_Products> tbl_Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Products>("MvcApplicationDBModel.pk_key1", "tbl_Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Products>("MvcApplicationDBModel.pk_key1", "tbl_Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplicationDBModel", Name="tbl_Relationship")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Relationship : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Relationship object.
        /// </summary>
        /// <param name="parentId">Initial value of the ParentId property.</param>
        /// <param name="children">Initial value of the Children property.</param>
        public static tbl_Relationship Createtbl_Relationship(global::System.Int32 parentId, global::System.Int32 children)
        {
            tbl_Relationship tbl_Relationship = new tbl_Relationship();
            tbl_Relationship.ParentId = parentId;
            tbl_Relationship.Children = children;
            return tbl_Relationship;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                if (_ParentId != value)
                {
                    OnParentIdChanging(value);
                    ReportPropertyChanging("ParentId");
                    _ParentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ParentId");
                    OnParentIdChanged();
                }
            }
        }
        private global::System.Int32 _ParentId;
        partial void OnParentIdChanging(global::System.Int32 value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Children
        {
            get
            {
                return _Children;
            }
            set
            {
                if (_Children != value)
                {
                    OnChildrenChanging(value);
                    ReportPropertyChanging("Children");
                    _Children = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Children");
                    OnChildrenChanged();
                }
            }
        }
        private global::System.Int32 _Children;
        partial void OnChildrenChanging(global::System.Int32 value);
        partial void OnChildrenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descriptions
        {
            get
            {
                return _Descriptions;
            }
            set
            {
                OnDescriptionsChanging(value);
                ReportPropertyChanging("Descriptions");
                _Descriptions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descriptions");
                OnDescriptionsChanged();
            }
        }
        private global::System.String _Descriptions;
        partial void OnDescriptionsChanging(global::System.String value);
        partial void OnDescriptionsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplicationDBModel", Name="tbl_Units")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Units : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Units object.
        /// </summary>
        /// <param name="unit_Id">Initial value of the Unit_Id property.</param>
        public static tbl_Units Createtbl_Units(global::System.Int32 unit_Id)
        {
            tbl_Units tbl_Units = new tbl_Units();
            tbl_Units.Unit_Id = unit_Id;
            return tbl_Units;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Unit_Id
        {
            get
            {
                return _Unit_Id;
            }
            set
            {
                if (_Unit_Id != value)
                {
                    OnUnit_IdChanging(value);
                    ReportPropertyChanging("Unit_Id");
                    _Unit_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Unit_Id");
                    OnUnit_IdChanged();
                }
            }
        }
        private global::System.Int32 _Unit_Id;
        partial void OnUnit_IdChanging(global::System.Int32 value);
        partial void OnUnit_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Unit_Name
        {
            get
            {
                return _Unit_Name;
            }
            set
            {
                OnUnit_NameChanging(value);
                ReportPropertyChanging("Unit_Name");
                _Unit_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Unit_Name");
                OnUnit_NameChanged();
            }
        }
        private global::System.String _Unit_Name;
        partial void OnUnit_NameChanging(global::System.String value);
        partial void OnUnit_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplicationDBModel", "pk_keyUnit", "tbl_Products")]
        public EntityCollection<tbl_Products> tbl_Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Products>("MvcApplicationDBModel.pk_keyUnit", "tbl_Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Products>("MvcApplicationDBModel.pk_keyUnit", "tbl_Products", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
